#*-----------------------------------------------------------------------------
#* Author: Boris Vinogradov(nis) : no111u3@gmail.com
#* File: Makefile
#* Type: Makefile
#* Project: STM32F4D
#* 2013
#*-----------------------------------------------------------------------------
# Build all libraries
all:
	$(MAKE) -C std_periph
	$(MAKE) -C xprintf

clean:
	$(MAKE) clean -C std_periph
	$(MAKE) -C xprintf